# Generated by Django 5.2 on 2025-04-22 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_coursevidesave'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='less_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
