# Generated by Django 5.2 on 2025-04-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_teacher_group_student_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course/media/student_img'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_image',
            field=models.ImageField(blank=True, null=True, upload_to='course/media/teacher_img'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course/media/course_img'),
        ),
    ]
