# Generated by Django 5.2 on 2025-04-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_student_image_teacher_teacher_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='works_as',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
