# Generated by Django 5.2 on 2025-04-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_course_image_alter_student_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
