# Generated by Django 5.2 on 2025-04-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_subjects_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lesson_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='student_study',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
