# Generated by Django 5.2 on 2025-04-16 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
