# Generated by Django 5.2 on 2025-04-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_alter_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='salary',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14),
        ),
    ]
