# Generated by Django 5.2 on 2025-04-17 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_teacher_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('video_file', models.FileField(upload_to='subject_videos/')),
                ('order', models.IntegerField(default=1)),
                ('description', models.TextField(blank=True, null=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='course.subjects')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
