# Generated by Django 5.2 on 2025-04-17 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_subjectvideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='course',
        ),
        migrations.RemoveField(
            model_name='group',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='subjectvideo',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='video',
            name='course',
        ),
        migrations.RemoveField(
            model_name='video',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='SubjectVideo',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
